### ISSUE TITLE
Module not found: Error: Package path . is not exported from package

### ISSUE THREAD

**Issue by Ishotihadus** [carhartl/typescript-cookie#146]
## Describe the bug
An error `Module not found: Error: Package path . is not exported from package /Users/ishotihadus/test/node_modules/typescript-cookie (see exports field in /Users/ishotihadus/test/node_modules/typescript-cookie/package.json)` occurs when building with webpack in some cases.

I think this is caused by package.json:
```json
"exports": {
    ".": {
      "import": "./dist/typescript-cookie.mjs",
    },
    "./package.json": "./package.json"
  },
```

I think there are two candidates to solve this problem.

```json
"exports": {
    ".": {
      "import": "./dist/typescript-cookie.mjs",
      "require": "./dist/typescript-cookie.mjs",
    },
    "./package.json": "./package.json"
  },
```

or 

```json
"exports": {
    ".": "./dist/typescript-cookie.mjs",
    "./package.json": "./package.json"
  },
```

If this restriction to `import` is not necessary, I think the above solutions are helpful.

### webpack.config.ts

```ts
import * as webpack from 'webpack';

const config: (env: any) => webpack.Configuration = (env) => {
  return {
    mode: 'production',
    entry: { 'test.js': './test.ts' },
    module: {
      rules: [
        {
          test: /\.(ts|tsx)$/i,
          exclude: /(^|\/)node_modules\//,
          use: [{ loader: 'ts-loader' }]
        }
      ]
    }
  };
};

export default config;
```

### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "commonjs",
    "strict": true,
  }
}
```

### test.ts

```ts
import { setCookie } from 'typescript-cookie';

setCookie('hoge', 'piyio', { expires: 60, secure: true, domain: 'example.com' });
```

## Expected behavior
Webpack can build without an error.

**Comment by netandreus** [comment]
+1 have the same issue

**Comment by carhartl** [comment]
The readme says:

> Support for ES modules only

I‘m guessing here: due to `"module": "commonjs"` in the tsconfig.json webpack attempts to load a cjs module (which is not supported)? Wouldn’t I need to add one to the dist in order to make this work?
