### ISSUE TITLE
Error TS7016 - Could not find a declaration file

### ISSUE THREAD

**Issue by davidkarlsson** [carhartl/typescript-cookie#171]
**Describe the bug**
If you use the new `nodeResolution` `bundler` option introduced in TypeScript 5.0 tsc will not find the declaration file for its imports and throw the following error:

```
error TS7016: Could not find a declaration file for module 'typescript-cookie'. 'D:/Test/.yarn/cache/typescript-cookie-npm-1.0.4-67c5369c2e-9fb4c76bd2.zip/node_modules/typescript-cookie/dist/typescript-cookie.mjs' implicitly has an 'any' type.
  There are types at 'D:/Test/.yarn/cache/typescript-cookie-npm-1.0.4-67c5369c2e-9fb4c76bd2.zip/node_modules/typescript-cookie/dist/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'typescript-cookie' library may need to update its package.json or typings.

1 import { getCookie, removeCookie, setCookie } from 'typescript-cookie';
```

**To Reproduce**

1. Add "typescript-cookie": "^1.0.4" and "typescript": "^5.0.2" to package.json
2. Set "moduleResolution": "bundler" in tsconfig.json
3. Import something from 'typescript-cookie': `import { setCookie } from 'typescript-cookie';`
4. Compile the file with tsc

**Expected behavior**
I expected tsc to find the type declaration file for 'typescript-cookie'.

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Pro 10.0.19043 Build 19043
- Version: typescript-cookie 1.0.4

**Comment by carhartl** [comment]
@davidkarlsson Could you post your entire tsconfig.json + package.json? I'm not able to reproduce this given the following:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "bundler"
  }
}
```

```json
{
  "name": "typescript-cookie-debug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "typescript": "^5.0.2",
    "typescript-cookie": "^1.0.4"
  }
}
```

```typescript
// src/index.ts
import { getCookie } from 'typescript-cookie'

console.log(getCookie('test'))
```

```bash
npx tsc --noEmit src/index.ts
```

**Comment by carhartl** [comment]
Ah, I think I figured it out: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

**Comment by carhartl** [comment]
9a7a54ed05378b2d249014dcc4c22fd19bad2ac4

**Comment by carhartl** [comment]
@davidkarlsson Can you try 1.0.5?

**Comment by davidkarlsson** [comment]
> @davidkarlsson Can you try 1.0.5?

Yes, 1.0.5 fixes this issue. Thank you!
