### ISSUE TITLE
Cannot find module 'typescript-cookie' or its corresponding type declarations.

### ISSUE THREAD

**Issue by danidomen** [carhartl/typescript-cookie#68]
**Describe the bug**
Cannot find module 'typescript-cookie' or its corresponding type declarations.

**To Reproduce**
1.- Install the latest release v1.0.0 via: npm i typescript-cookie
2.- Import the getCookie as the documentation says
3.- VSC display error about missing library or type declarations

**Expected behavior**
Expect no error on a TS library about missing types. Maybe I'm doing something wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/5998908/149953659-60d865e8-07f1-4aac-8747-ba5751de9727.png)

**Desktop (please complete the following information):**
- OS: Windows 10

**Comment by TannerDale** [comment]
Also failing on macOS Big Sur 11.5.2

**Comment by carhartl** [comment]
Should be fixed in https://github.com/carhartl/typescript-cookie/releases/tag/v1.0.2
