### ISSUE TITLE
Customizing getCookie return types

### ISSUE THREAD

**Issue by sambecker** [carhartl/typescript-cookie#85]
**Is your feature request related to a problem? Please describe.**
Would love to be able to add types to `getCookie` when I know what to expect

**Describe the solution you'd like**
Add generics to the signature: `getCookie<KnownType>()`

**Describe alternatives you've considered**
`getCookie() as KnownType | undefined`

**Additional context**
Not sure I'm up to it, but would be open to submitting a PR!

**Comment by carhartl** [comment]
The returned type currently depends on the decoder:

https://github.com/carhartl/typescript-cookie/blob/135a52ba38674a305a90a83860616a3856277cc1/src/api.ts#L132-L135

So this already works:

```typescript
const number: number = getCookie("c", { decodeValue: (value) => parseInt(value) });
```

Does that help?

**Comment by sambecker** [comment]
Thank you, that is clarifying! I didn't realize it worked that way.

For my values, I'm not decoding anything but rather guaranteeing a narrow set of strings.

**What happens now**
```ts
type CookieResponse = 'one' | 'two' | 'three';
const cookie: string | undefined = getCookie(COOKIE_KEY);
```

**What I was hoping to do**
```ts
type CookieResponse = 'one' | 'two' | 'three';
const cookie: CookieResponse | undefined = getCookie<CookieResponse>(COOKIE_KEY);
```

**Passing an empty decoder does indeed work, but feels less than ideal?**
```ts
type CookieResponse = 'one' | 'two' | 'three';
const cookie: CookieResponse | undefined = getCookie(COOKIE_KEY, {
  decodeValue: x => x as CookieResponse,
});
```
